/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author R.M.A
 */
public class LibrarianReg extends javax.swing.JFrame {
String Libid, Fname, Lname, AddL1, AddL2, City, Gender, ContactNo, DOB,NICNO,Password;
        
    /**
     * Creates new form LibrarianReg
     */
    public LibrarianReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtlib_id = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtaddl1 = new javax.swing.JTextField();
        txtaddl2 = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtcontactno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btninsert = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        rdbmale = new javax.swing.JRadioButton();
        rdbfemale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtnicno = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        txtpw = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllibrarian = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText(" Librarian Registration");

        txtlib_id.setText(" ");
        txtlib_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlib_idKeyPressed(evt);
            }
        });

        txtfname.setText(" ");

        txtlname.setText(" ");

        txtaddl1.setText(" ");

        txtaddl2.setText(" ");

        txtcity.setText(" ");

        txtcontactno.setText(" ");
        txtcontactno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcontactnoKeyTyped(evt);
            }
        });

        jLabel2.setText("Librarian Id");

        jLabel3.setText(" First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Address Line 1");

        jLabel6.setText("Address Line 2");

        jLabel7.setText("City");

        jLabel8.setText("DOB");

        jLabel10.setText("Gender");

        jLabel11.setText("Contact No");

        btninsert.setText("Insert");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbmale);
        rdbmale.setText("Male");

        buttonGroup1.add(rdbfemale);
        rdbfemale.setText("Female");

        jLabel9.setText("NIC No");

        txtnicno.setText(" ");

        jLabel12.setText("Password");

        txtpw.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rdbmale, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(rdbfemale, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtfname)
                    .addComponent(txtlib_id)
                    .addComponent(txtlname)
                    .addComponent(txtaddl1)
                    .addComponent(txtaddl2)
                    .addComponent(txtcity)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(44, 44, 44))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(64, 64, 64)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcontactno, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtpw, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btndelete)
                                    .addComponent(txtnicno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addComponent(btnclear))))
                    .addComponent(jLabel12))
                .addGap(83, 83, 83))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addComponent(btninsert)
                .addGap(38, 38, 38)
                .addComponent(btnupdate)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlib_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtcontactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtnicno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(txtpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaddl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtaddl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbmale)
                    .addComponent(rdbfemale)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninsert)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnclear))
                .addGap(73, 73, 73))
        );

        tbllibrarian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbllibrarian);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(90, 90, 90))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        if (this.txtfname.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null, "First Name cannot be black");
        }
       
       else if (this.txtlib_id.getText().isEmpty()==true)
       {
           JOptionPane.showMessageDialog(null, "Librarian Id cannot be black");
       }
       
       else
       {
           
        Libid = this.txtlib_id.getText();
        Fname = this.txtfname.getText();
        Lname = this.txtlname.getText();
        AddL1 = this.txtaddl1.getText();
        AddL2 = this.txtaddl2.getText();
        City = this.txtcity.getText();
         
        NICNO=this.txtnicno.getText();
        Password= this.txtpw.getText();
        ContactNo = this.txtcontactno.getText(); 
        
         SimpleDateFormat jd = new SimpleDateFormat("yyyy-MM-dd"); 
        DOB = jd.format(this.jXDatePicker1.getDate());
        
        if(this.rdbmale.isSelected()==true){
            Gender = "Male";
        }else if(this.rdbfemale.isSelected()==true){
            Gender = "Female";
        }else{
            Gender = "null";
            JOptionPane.showMessageDialog(null, "Please Select Gender Option");
        }
        
         
        
        DBCon.DBConnection();
                
        {
      try{
            Statement st = DBCon.con.createStatement();
            st.executeUpdate("Insert into librarian values('"+Libid+"','"+Fname+"','"+Lname+"','"+AddL1+"','"+AddL2+"','"+City+"','"+DOB+"','"+Gender+"','"+NICNO+"','"+Password+"')");
            
             
            Statement st1 = DBCon.con.createStatement();
           st1.executeUpdate("Insert into lib_contact values('"+Libid+"','"+ContactNo+"')");
           JOptionPane.showMessageDialog(null, "Data Inserted Successfully");
            LoadTable();
            DBCon.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }                                         
       }
    
      
         
        
        
        
    }//GEN-LAST:event_btninsertActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
         Libid = this.txtlib_id.getText();
        Fname = this.txtfname.getText();
        Lname = this.txtlname.getText();
        AddL1 = this.txtaddl1.getText();
        AddL2 = this.txtaddl2.getText();
        City = this.txtcity.getText();
         
        NICNO=this.txtnicno.getText();
        Password= this.txtpw.getText();
        ContactNo = this.txtcontactno.getText(); 
        
         SimpleDateFormat jd = new SimpleDateFormat("yyyy-MM-dd"); 
        DOB = jd.format(this.jXDatePicker1.getDate());
        
            
        
        if(this.rdbmale.isSelected()==true){
            Gender = "Male";
        }else if(this.rdbfemale.isSelected()==true){
            Gender = "Female";
        }else{
            Gender = "null";
            JOptionPane.showMessageDialog(null, "Please Select Gender Option");
        }
        
        DBCon.DBConnection();
                
        {
      try{
            Statement st = DBCon.con.createStatement();
            st.executeUpdate("UPDATE librarian SET  Lib_Fname='"+Fname+"',Lib_Lname='"+Lname+"', Lib_AddressL1='"+AddL1+"',Lib_AddressL2='"+AddL2+"',Lib_City='"+City+"',DOB='"+DOB+"', Gender='"+Gender+"',LIB_NICNo='"+NICNO+"',Lib_NICNo='"+NICNO+"',Password='"+Password+"' WHERE Lib_id='"+Libid+"'");
            
             Statement st1 = DBCon.con.createStatement();
            st1.executeUpdate("UPDATE lib_contact SET  Lib_ContactNo='"+ContactNo+"' WHERE Lib_id='"+Libid+"'");
            
            JOptionPane.showMessageDialog(null, "Data Updated Successfully");
             ClearData();
            LoadTable();
            DBCon.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }                                         
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         Libid = this.txtlib_id.getText();
         
        
        
        DBCon.DBConnection();
                
        {
      try{
            Statement st = DBCon.con.createStatement();
            st.executeUpdate("DELETE FROM librarian where Lib_id='"+Libid+"'");
            
            Statement st1 = DBCon.con.createStatement();
            st1.executeUpdate("DELETE FROM lib_contact where Lib_id='"+Libid+"'");
            
            JOptionPane.showMessageDialog(null, "Data deleted Successfully");
            ClearData();
            LoadTable(); 
            DBCon.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }                                         
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        ClearData();
}
      void ClearData(){
        this.txtlib_id.setText("");
        this.txtfname.setText("");
        this.txtlname.setText("");
        this.txtaddl1.setText("");
        this.txtaddl2.setText("");
        this.txtcity.setText("");
        this.txtcontactno.setText("");
        this.txtpw.setText("");
         
        this.jXDatePicker1.setDate(null);
        
        this.txtnicno.setText(""); 
        this.buttonGroup1.clearSelection();
    }                                        

     void LoadTable()
     {
      DefaultTableModel dm = new DefaultTableModel();
      dm.addColumn("Librarianid");
      dm.addColumn("Fname");
      dm.addColumn("Lname");
      dm.addColumn("Addl1");
      dm.addColumn("Addl2");
      dm.addColumn("City");
      dm.addColumn("DOB");
       
      dm.addColumn("Gender");
       dm.addColumn("Password");
      dm.addColumn("ContactNo");
      dm.addColumn("NICNO");
      
      String Query= ("SELECT *, Lib_ContactNo FROM librarian INNER JOIN lib_contact ON librarian.Lib_id = lib_contact.Lib_id WHERE librarian.Lib_id = '"+Libid+"'");
      DBCon.DBConnection();
      {
          try
          {
            Statement st=DBCon.con.prepareStatement(Query);
            ResultSet rs = st. executeQuery (Query);
            
            while (rs.next())
            {
                String memid = rs.getString("Lib_id");
                String fname = rs.getString("Lib_Fname");
                String lname = rs.getString("Lib_Lname");
                String addl1= rs.getString("Lib_AddressL1");
                String addl2 = rs.getString("Lib_AddressL2");
                String city = rs.getString("Lib_City");
                String dob = rs.getString("DOB");
                 
                String gen = rs.getString("Gender");
                String pw = rs.getString("Password"); 
                String conno = rs.getString("Lib_ContactNo");
                String nic = rs.getString("Lib_NICNo");  
                
                dm.addRow(new String[]{memid,fname,lname,addl1,addl2,city,dob,gen,conno,nic,pw});
            }
            this.tbllibrarian.setModel(dm);
             
          }
           catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
          }
      }
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtlib_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlib_idKeyPressed
        // TODO add your handling code here:
         
         
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        
        Libid=this.txtlib_id.getText();
        
       
         
        String Query = ("SELECT *, Lib_ContactNo FROM librarian INNER JOIN lib_contact ON librarian.Lib_id = lib_contact.Lib_id WHERE librarian.Lib_id = '"+Libid+"'");
         
        
        DBCon.DBConnection();
        {
        try
        {
        Statement st = DBCon.con.createStatement();
        ResultSet rs = st.executeQuery(Query);
        while(rs.next())
        {
        this.txtfname.setText(rs.getString("Lib_Fname"));
        this.txtlname.setText(rs.getString("Lib_Lname"));
        this.txtaddl1.setText(rs.getString("Lib_AddressL1"));
        this.txtaddl2.setText(rs.getString("Lib_AddressL2"));
        this.txtcity.setText(rs.getString("Lib_City"));
         
        this.jXDatePicker1.setDate(rs.getDate("DOB"));
         
        this.txtcontactno.setText(rs.getString("Lib_ContactNo"));
        this.txtnicno.setText(rs.getString("Lib_NICNo")); 
        this.txtpw.setText(rs.getString("Password"));   
        
        if(rs.getString("Gender").equalsIgnoreCase("Male"))
        {
            this.rdbmale.setSelected(true);
        }
      else
        {
            this.rdbfemale.setSelected(true);
        }
        }
        DBCon.con.close();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        }
        }
    }//GEN-LAST:event_txtlib_idKeyPressed

    private void txtcontactnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactnoKeyTyped
        // TODO add your handling code here:
         

    }//GEN-LAST:event_txtcontactnoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JRadioButton rdbfemale;
    private javax.swing.JRadioButton rdbmale;
    private javax.swing.JTable tbllibrarian;
    private javax.swing.JTextField txtaddl1;
    private javax.swing.JTextField txtaddl2;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlib_id;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtnicno;
    private javax.swing.JTextField txtpw;
    // End of variables declaration//GEN-END:variables
}
