/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;
 
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
/**
/**
 *
 * @author R.M.A
 */
public class LibrarianBorrowBook extends javax.swing.JFrame {
String bookid, memid, duedate, returndate, borrowdate,lid;
int noofbook,available;
 double Delayeddays, amount_charged_perday, fine_charged,No_of_bookstoreturn;
    /**
     * Creates new form LibrarianBorrowBook
     */
    public LibrarianBorrowBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtmemid = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        txtdeladate = new javax.swing.JTextField();
        txtamountcha = new javax.swing.JTextField();
        txtfc = new javax.swing.JTextField();
        btninsert = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker3 = new org.jdesktop.swingx.JXDatePicker();
        txtnb = new javax.swing.JTextField();
        txtnoofbook = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jXDatePicker4 = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtlid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtavailable = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel10.setText(" Return Book");

        jLabel11.setText("Borrow Date");

        jLabel13.setText("Return Date");

        jLabel14.setText("Delayed Days");

        jLabel15.setText("Amount Charged Per Day");

        jLabel16.setText(" Number of Books to Return");

        jLabel17.setText("Fine Charged");

        txtmemid.setText(" ");
        txtmemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmemidKeyPressed(evt);
            }
        });

        txtbookid.setText(" ");
        txtbookid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbookidMouseClicked(evt);
            }
        });
        txtbookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbookidKeyPressed(evt);
            }
        });

        txtdeladate.setText(" ");
        txtdeladate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdeladateMouseClicked(evt);
            }
        });

        txtamountcha.setText(" ");

        txtfc.setText(" ");
        txtfc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfcMouseClicked(evt);
            }
        });

        btninsert.setText(" Insert");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });

        btnupdate.setText(" Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jButton8.setText("Clear");

        jLabel1.setText("Member Id");

        jLabel2.setText("Book Id");

        txtnb.setText(" ");
        txtnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnbActionPerformed(evt);
            }
        });

        txtnoofbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnoofbookMouseClicked(evt);
            }
        });
        txtnoofbook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnoofbookKeyPressed(evt);
            }
        });

        jLabel4.setText("No of Books");

        jLabel6.setText(" Due Date");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel12.setText(" Borrow Books");

        jLabel3.setText("Librarian id");

        txtlid.setText(" ");

        jLabel7.setText("Available");

        txtavailable.setText(" ");

        jButton1.setText("Back");

        jButton2.setText("Exit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(675, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btninsert)
                                .addGap(34, 34, 34)
                                .addComponent(btnupdate)
                                .addGap(32, 32, 32)
                                .addComponent(jButton8)
                                .addGap(103, 103, 103))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(91, 91, 91)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jXDatePicker4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtbookid, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                        .addComponent(txtnoofbook, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                        .addComponent(jXDatePicker3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                        .addComponent(txtlid)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                    .addComponent(txtmemid, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtfc, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtamountcha, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                            .addComponent(txtnb, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                            .addComponent(txtdeladate, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                            .addComponent(txtavailable)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)))))
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addComponent(jLabel12)
                    .addContainerGap(583, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtavailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtlid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14)
                    .addComponent(txtdeladate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnoofbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15)
                    .addComponent(txtamountcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtnb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(102, 102, 102)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninsert)
                    .addComponent(btnupdate)
                    .addComponent(jButton8)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel12)
                    .addContainerGap(563, Short.MAX_VALUE)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnoofbookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoofbookKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtnoofbookKeyPressed

    private void txtnoofbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnoofbookMouseClicked
        // TODO add your handling code here:
          
             
               int available = Integer.parseInt(txtavailable.getText());
              int noofbook = Integer.parseInt(txtnoofbook.getText()) ;
              
            if(available >=10   ){
        int Tot = ((available) + (noofbook));
        
        txtavailable.setText(""+Tot);}
             else{
            JOptionPane.showMessageDialog(null, "There are between 1-10 books");
        }
       bookid= this.txtbookid.getText();
           available = Integer.parseInt(this.txtavailable.getText());
        
        DBCon.DBConnection();
                
        {
      try{
            Statement st = DBCon.con.createStatement();
            st.executeUpdate("UPDATE book SET available="+available+" WHERE Book_id='"+bookid+"'");
            
        //JOptionPane.showMessageDialog(null, "Data Updated Successfully");
              
            DBCon.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        } 
                       

    }//GEN-LAST:event_txtnoofbookMouseClicked

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:

        if (this.txtbookid.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null, "Book id cannot be black ");
        }

        else if (this.txtmemid.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null, "Member id cannot be black");
        }

        else
        {

            memid= this.txtmemid.getText();
            bookid = this.txtbookid.getText();
            lid = this.txtlid.getText();
            noofbook = Integer.parseInt(this.txtnoofbook.getText());

            SimpleDateFormat jd = new SimpleDateFormat("yyyy-MM-dd");
            borrowdate = jd.format(this.jXDatePicker3.getDate());

            SimpleDateFormat db = new SimpleDateFormat("yyyy-MM-dd");
            duedate = db.format(this.jXDatePicker4.getDate());
            

            DBCon.DBConnection();

            {
                try{
                    Statement st = DBCon.con.createStatement();
                    st.executeUpdate("Insert into borrow_by values('"+lid+"','"+bookid+"','"+memid+"','"+borrowdate+"','"+duedate+"','"+returndate+"','"+Delayeddays+"',"+noofbook+","+amount_charged_perday+","+fine_charged+","+No_of_bookstoreturn+")");

                    JOptionPane.showMessageDialog(null, "Data Inserted Successfully");

                    DBCon.con.close();
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
        memid = this.txtmemid.getText();
         
        
        
        DBCon.DBConnection();
                
        {
      try{
            Statement st = DBCon.con.createStatement();
            st.executeUpdate("DELETE FROM reserve where Mem_id='"+memid+"'");
            
            
            
            //JOptionPane.showMessageDialog(null, "Data deleted Successfully");
              
            DBCon.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }                                         
    }//GEN-LAST:event_btninsertActionPerformed

    private void txtfcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfcMouseClicked
        // TODO add your handling code here:
        double fine, amountcpd, nb, delayed_days;

        {
            amountcpd  = Double.parseDouble(txtamountcha.getText());
            nb =  Double.parseDouble(txtnb.getText());
            delayed_days =  Double.parseDouble(txtdeladate.getText());
            fine = amountcpd* nb* delayed_days;

            txtfc.setText(""+fine);
        }
    }//GEN-LAST:event_txtfcMouseClicked

    private void txtdeladateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdeladateMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String date = sdf.format(this.jXDatePicker1.getDate());

        SimpleDateFormat dtf = new SimpleDateFormat("dd-MM-yyyy");
        String date2 = dtf.format(this.jXDatePicker4.getDate());

        try
        {
            java.util.Date d1 = sdf. parse (date);
            java.util.Date d2 = dtf. parse (date2);

            long days = (d1.getTime()- d2.getTime())/(24*60*60*1000);
            txtdeladate.setText(""+days);

        }
        catch (ParseException pe)
        {
            JOptionPane.showMessageDialog(null, pe.getMessage());
        }
    }//GEN-LAST:event_txtdeladateMouseClicked

    private void txtbookidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbookidKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtbookidKeyPressed

    private void txtmemidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmemidKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            memid=this.txtmemid.getText();

            String Query = ("SELECT * FROM borrow_by WHERE Mem_id='"+memid+"'");

            DBCon.DBConnection();
            {
                try
                {
                    Statement st = DBCon.con.createStatement();
                    ResultSet rs = st.executeQuery(Query);
                    while(rs.next())
                    {
                        this.txtbookid.setText(rs.getString("Book_id"));
                        
                        this.txtlid.setText(rs.getString("Lib_id"));
                        
                        this.jXDatePicker3.setDate(rs.getDate("Borrow_Date"));
                        this.jXDatePicker4.setDate(rs.getDate("Due_Date"));
                        this.txtnoofbook.setText(rs.getString("No_of_Books"));
                        
                         
                         

                    }
                    DBCon.con.close();
                }
                catch(SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }

            }
        }
    }//GEN-LAST:event_txtmemidKeyPressed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        memid= this.txtmemid.getText();
            bookid = this.txtbookid.getText();
            

            noofbook = Integer.parseInt(this.txtnoofbook.getText());

            SimpleDateFormat jd = new SimpleDateFormat("yyyy-MM-dd");
            borrowdate = jd.format(this.jXDatePicker3.getDate());

            SimpleDateFormat db = new SimpleDateFormat("yyyy-MM-dd");
            duedate = db.format(this.jXDatePicker4.getDate());
            
                SimpleDateFormat rd = new SimpleDateFormat("yyyy-MM-dd");
            returndate = rd.format(this.jXDatePicker1.getDate());
            
            
        fine_charged = Double.parseDouble(this.txtfc.getText());
        amount_charged_perday = Double.parseDouble(this.txtamountcha.getText());
        Delayeddays = Double.parseDouble(this.txtdeladate.getText());
        No_of_bookstoreturn = Double.parseDouble(this.txtnb.getText());
    
        
        DBCon.DBConnection();
                
        {
      try{
            Statement st = DBCon.con.createStatement();
            st.executeUpdate("UPDATE borrow_by SET  Due_Date='"+duedate+"',Return_Date='"+returndate+"',Delayed_Days="+Delayeddays+",No_of_Books="+noofbook+", Amount_Charged_perday="+amount_charged_perday+",Fine_Charged="+fine_charged+",No_of_BookstoReturn='"+No_of_bookstoreturn+"' WHERE Mem_id='"+memid+"'");
            
             
            JOptionPane.showMessageDialog(null, "Data Updated Successfully");
              
            DBCon.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    } 
       
              
             
              
     
             
               
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnbActionPerformed

    private void txtbookidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbookidMouseClicked
        // TODO add your handling code here:
         
        bookid=this.txtbookid.getText();
        
        String Query = "SELECT* FROM book where Book_id='"+bookid+"'";
        
        DBCon.DBConnection();
        {
        try
        {
        Statement st = DBCon.con.createStatement();
        ResultSet rs = st.executeQuery(Query);
        while(rs.next())
        {
         
        this.txtavailable.setText(rs.getString("available"));
         
         
        }
        DBCon.con.close();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        }
        
     
    }//GEN-LAST:event_txtbookidMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianBorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianBorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianBorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianBorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianBorrowBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker4;
    private javax.swing.JTextField txtamountcha;
    private javax.swing.JTextField txtavailable;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtdeladate;
    private javax.swing.JTextField txtfc;
    private javax.swing.JTextField txtlid;
    private javax.swing.JTextField txtmemid;
    private javax.swing.JTextField txtnb;
    private javax.swing.JTextField txtnoofbook;
    // End of variables declaration//GEN-END:variables
}
