/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author R.M.A
 */
public class MemberReserveBook extends javax.swing.JFrame {
String reservedate,memid,bookid;
        int noofbooks,available;
    /**
     * Creates new form MemberReserveBook
     */
    public MemberReserveBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmemid = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        btninsert = new javax.swing.JButton();
        txtnb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtavailable = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Reserve Book");

        jLabel2.setText("Member Id");

        jLabel3.setText("Book Id");

        jLabel4.setText("Reserve Date");

        txtmemid.setText(" ");
        txtmemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmemidKeyPressed(evt);
            }
        });

        txtbookid.setText(" ");
        txtbookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbookidKeyPressed(evt);
            }
        });

        btninsert.setText("Insert");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });

        txtnb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnbKeyPressed(evt);
            }
        });

        jLabel5.setText("No of Books");

        jLabel6.setText("Available");

        txtavailable.setText(" ");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnb)
                            .addComponent(txtbookid)
                            .addComponent(txtmemid)
                            .addComponent(txtavailable)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btninsert)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtavailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninsert)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(25, 25, 25))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Exit");

        jButton3.setText("Back");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbookidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbookidKeyPressed
        // TODO add your handling code here:
         
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        
        bookid=this.txtbookid.getText(); 
        String Query = ("SELECT * FROM book WHERE Book_id='"+bookid+"'");
         
        DBCon.DBConnection();
        {
        try
        {
        Statement st = DBCon.con.createStatement();
        ResultSet rs = st.executeQuery(Query);
        while(rs.next())
        {
        this.txtavailable.setText(rs.getString("Available"));
         

        }
        DBCon.con.close();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        }
        }  
        
    }//GEN-LAST:event_txtbookidKeyPressed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        if (this.txtbookid.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null, "Book id cannot be black ");
        }
       
       else if (this.txtmemid.getText().isEmpty()==true)
       {
           JOptionPane.showMessageDialog(null, "Member id cannot be black");
       }
       
       else
       {
           
        memid= this.txtmemid.getText();
        bookid = this.txtbookid.getText();
        noofbooks = Integer.parseInt(this.txtnb.getText());
        
         
        
        SimpleDateFormat jd = new SimpleDateFormat("yyyy-MM-dd"); 
        reservedate = jd.format(this.jXDatePicker1.getDate());
        
  
        DBCon.DBConnection();
                
        {
      try{
            Statement st = DBCon.con.createStatement();
            st.executeUpdate("Insert into reserve values('"+bookid+"','"+memid+"','"+reservedate+"',"+noofbooks+")");
            
              
            
            JOptionPane.showMessageDialog(null, "Data Inserted Successfully");
            
            DBCon.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }                                         
       }
    }//GEN-LAST:event_btninsertActionPerformed

    private void txtnbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnbKeyPressed
        // TODO add your handling code here:
    if(evt.getKeyCode()== KeyEvent.VK_ENTER){
             
    int available = Integer.parseInt(txtavailable.getText());
    int noofbook = Integer.parseInt(txtnb.getText()) ;
              
    if(available >=10   ){
    int Tot = ((available) - (noofbook));
        
    txtavailable.setText(""+Tot);}
    else{
    JOptionPane.showMessageDialog(null, "There are between 1-10 books");
        }
    bookid= this.txtbookid.getText();
    available = Integer.parseInt(this.txtavailable.getText());
        
    DBCon.DBConnection();
                
        {
      try{
     Statement st = DBCon.con.createStatement();
st.executeUpdate("UPDATE book SET available="+available+" WHERE Book_id='"+bookid+"'");
            
        //JOptionPane.showMessageDialog(null, "Data Updated Successfully");
              
            DBCon.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        } 
         }              
    }//GEN-LAST:event_txtnbKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          memid= this.txtmemid.getText();
        bookid = this.txtbookid.getText();
        noofbooks = Integer.parseInt(this.txtnb.getText());
        
         
        
        SimpleDateFormat jd = new SimpleDateFormat("yyyy-MM-dd"); 
        reservedate = jd.format(this.jXDatePicker1.getDate());
            
        
       
        DBCon.DBConnection();
                
        {
      try{
            Statement st = DBCon.con.createStatement();
            st.executeUpdate("UPDATE reserve SET  Book_id='"+bookid+"',Reserve_Date='"+reservedate+"', No_of_Books='"+noofbooks+"' WHERE Mem_id='"+memid+"'");
            
              
            JOptionPane.showMessageDialog(null, "Data Updated Successfully");
          
            LoadTable();
            DBCon.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }                                         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmemidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmemidKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            memid=this.txtmemid.getText();

            String Query = "SELECT* FROM reserve";

            DBCon.DBConnection();
            {
                try
                {
                    Statement st = DBCon.con.createStatement();
                    ResultSet rs = st.executeQuery(Query);
                    while(rs.next())
                    {

                        this.jXDatePicker1.setDate(rs.getDate("Reserve_Date"));
                         
                        this.txtnb.setText(rs.getString("No_of_Books"));
                        this.txtbookid.setText(rs.getString("Book_id"));
                         
                    }
                    DBCon.con.close();
                }
                catch(SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }

     
    }//GEN-LAST:event_txtmemidKeyPressed

     void LoadTable()
     {
      DefaultTableModel dm = new DefaultTableModel();
      dm.addColumn("Memberid");
      dm.addColumn("Bookid");
      dm.addColumn("Reserve_Date");
      dm.addColumn("No_of_Books");
       
      
      String Query= ("SELECT * FROM reserve");
      DBCon.DBConnection();
      {
          try
          {
            Statement st=DBCon.con.prepareStatement(Query);
            ResultSet rs = st. executeQuery (Query);
            
            while (rs.next())
            {
                String memid = rs.getString("Mem_id");
                String bookid = rs.getString("Book_id");
                String rd = rs.getString("Reserve_Date");
                String nb= rs.getString("No_of_Books");
                 
                
                dm.addRow(new String[]{memid,bookid,rd,nb});
            }
            this.jTable1.setModel(dm);
             
          }
           catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
          }
      }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberReserveBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberReserveBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberReserveBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberReserveBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberReserveBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninsert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTextField txtavailable;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtmemid;
    private javax.swing.JTextField txtnb;
    // End of variables declaration//GEN-END:variables
}
